In [204]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.animation as animation
import matplotlib
import time
# from timing import time_it as tt
from mpl_toolkits.mplot3d import Axes3D
import math

In [205]:
#part (a)

In [206]:
theta = np.array([3, 1, 2]).reshape((3, 1))
print(theta)

[[3]
 [1]
 [2]]


In [207]:
def sample(count=1000000):
    x0 = np.ones((count)).reshape(count, 1)
    x1 = np.random.normal(3, 2, count).reshape(count, 1)
    x2 = np.random.normal(-1, 2, count).reshape(count, 1)
    error = np.random.normal(0, math.sqrt(2), count).reshape(count, 1)
    
    desX  = np.hstack((x0, x1, x2))
    y = np.dot(desX, theta) + error
    return (desX, y)

In [208]:
d = sample(20)[0]

In [209]:
d

array([[ 1.        ,  4.12777928, -1.45400984],
       [ 1.        , -2.62114939, -2.92752471],
       [ 1.        ,  1.67848114, -0.39575067],
       [ 1.        ,  3.50359325, -1.88203021],
       [ 1.        ,  5.3999881 , -2.69264211],
       [ 1.        ,  3.94499303, -1.66041644],
       [ 1.        ,  2.64282669,  1.77987591],
       [ 1.        ,  2.50904538, -0.5360578 ],
       [ 1.        , -1.50078985, -3.50251491],
       [ 1.        ,  4.15248444,  1.43932515],
       [ 1.        ,  1.19543708,  1.33596073],
       [ 1.        , -0.97936697, -2.64681055],
       [ 1.        ,  2.05215915,  0.35213951],
       [ 1.        ,  4.55658133,  1.9101288 ],
       [ 1.        ,  5.37829108, -0.95210736],
       [ 1.        ,  1.91781161, -1.23075164],
       [ 1.        ,  3.07625183, -0.17122685],
       [ 1.        ,  2.21484844, -1.1005943 ],
       [ 1.        ,  6.25637107, -1.91259789],
       [ 1.        ,  3.32789486, -0.95148709]])

In [210]:
d[0:5]

array([[ 1.        ,  4.12777928, -1.45400984],
       [ 1.        , -2.62114939, -2.92752471],
       [ 1.        ,  1.67848114, -0.39575067],
       [ 1.        ,  3.50359325, -1.88203021],
       [ 1.        ,  5.3999881 , -2.69264211]])

In [211]:
eta = 0.1

In [212]:
def cost(X, Y, theta):
	'''Input:
		X = Design Matrix 
		# h= vector of hypothesis for each exampla x_i (i=0...m) (Vector of Xθ)
		Y= Output vector
        theta = parameter matrix
            [θ0]
            [θ1]
            [θ2]
		Returns the cost J(θ)
		J(θ) = 1/2m * Σ(hθ(x_i) - y_i)^2 (i=0...m)
		or
		J(θ) = 1/2m * [(Xθ - Y)^t * (Xθ - Y)]
	'''
	m = len(Y)
	h = np.dot(X, theta)

	return (1 / ((2 * m)) * np.sum((h - Y) ** 2))


In [216]:
cost_arr = []
theta0_arr = []
theta1_arr = []
def stochasticGradientDescent(X, Y, eta, r):
    print(X.shape, Y.shape)
    '''
    Input:
        X= Design Matrix of x
        Y= Output
        eta = Learning rate

    output: θ vector
        θ := θ - eta * (1/m) * X^t * (Xθ - Y)
    '''
    m = len(Y)
    theta_prev = np.zeros((X.shape[1], 1))
    for i in range(0, 2):
        for b in range(0, m//r + 1):
#             print(theta_prev)
            cost_arr.append(cost(X, Y, theta_prev))
            theta0_arr.append(theta_prev[0][0])
            theta1_arr.append(theta_prev[1][0])
            
            if b == m//r:
                rem = Y.shape[0] - m//r * r
                if rem == 0:
                    continue
                Xb = X[b*r:][:]
                Yb = Y[b*r:][:]
            else:
                rem = r
                Xb = X[b*r:b*r+r][:]
                Yb = Y[b*r:b*r+r][:]

            h = np.dot(Xb, theta_prev)
#             print("-"*30)
#             print(Yb.shape)

            theta_current = theta_prev - (1 / rem) * eta *  np.dot(np.transpose(Xb), (h - Yb))
            theta_prev = theta_current
            
            


    return theta_current
    

In [217]:
sample_data = sample(1000000)
sample_x = sample_data[0]
sample_y = sample_data[1]
r = 100

In [218]:
theta_sgd =  stochasticGradientDescent(sample_x, sample_y, eta, r)

(1000000, 3) (1000000, 1)


In [219]:
theta_sgd

array([[2.98927424],
       [0.95483367],
       [2.04992177]])

In [220]:
cost(sample_x, sample_y, np.array([0,0,0]).reshape(3,1))

18.96348075888236

In [221]:
cost(sample_x, sample_y, np.array([3,1,2]).reshape(3,1))

1.0027637218512038

In [222]:
cost(sample_x, sample_y, theta_sgd)

1.031056233279816

In [223]:
#(c) part

In [225]:
desX

NameError: name 'desX' is not defined

In [226]:
sample_y

array([[ 8.81574602],
       [16.28115033],
       [-4.53325276],
       ...,
       [ 7.37730804],
       [ 6.75661557],
       [ 2.61669033]])

In [236]:
np.random.shuffle(sample_y)

In [237]:
sample_y

array([[10.00618943],
       [ 8.40523629],
       [ 2.74008677],
       ...,
       [ 0.19263127],
       [-0.69958061],
       [ 3.05899404]])

In [231]:
print(cc)

None


In [238]:
sample_x

array([[ 1.        ,  2.61085723,  1.9567683 ],
       [ 1.        ,  7.59329478,  2.03047323],
       [ 1.        , -2.33606133, -1.71466582],
       ...,
       [ 1.        ,  1.72334903,  2.75254605],
       [ 1.        ,  0.08830156,  0.80618514],
       [ 1.        ,  6.69502038, -2.17430155]])

In [241]:
xy = np.hstack((sample_x, sample_y))

In [242]:
xy

array([[ 1.        ,  2.61085723,  1.9567683 , 10.00618943],
       [ 1.        ,  7.59329478,  2.03047323,  8.40523629],
       [ 1.        , -2.33606133, -1.71466582,  2.74008677],
       ...,
       [ 1.        ,  1.72334903,  2.75254605,  0.19263127],
       [ 1.        ,  0.08830156,  0.80618514, -0.69958061],
       [ 1.        ,  6.69502038, -2.17430155,  3.05899404]])

In [243]:
np.random.shuffle(xy)

In [244]:
xy

array([[ 1.        ,  3.01618942, -1.80351604,  0.4980087 ],
       [ 1.        ,  2.14951089,  0.25643015,  6.27626716],
       [ 1.        ,  4.18387032, -1.29255475, -0.01212842],
       ...,
       [ 1.        ,  3.75173684, -0.59722351, -1.03957543],
       [ 1.        ,  3.84792989, -2.58213865,  6.2944381 ],
       [ 1.        ,  1.23866665,  0.7927699 , -1.18405637]])

In [248]:
xy[:,(0,1)]

array([[1.        , 3.01618942],
       [1.        , 2.14951089],
       [1.        , 4.18387032],
       ...,
       [1.        , 3.75173684],
       [1.        , 3.84792989],
       [1.        , 1.23866665]])